@startgantt planning
printscale weekly with calendar date zoom 1.5
hide footbox
saturdays are closed
sundays are closed

2023-10-15 to 2023-10-20 are closed
2023-12-25 to 2024-1-5 are closed
Project starts 2023-9-18

today is colored in Salmon


-- Documentation --
[PVA maken] starts at 2023-9-18 and ends at 2024-2-2
[Use case diagram] starts at 2023-10-2 and ends at 2024-2-2
[Use case flows] starts at 2023-10-9 and ends at 2024-2-2

-- Development --
[Communicatie] starts at 2023-10-16 and lasts 1 weeks
[Control Center designen] starts at [Communicatie]'s end and lasts 9 weeks
[Control Center Basic] starts 7 days after [Communicatie]'s end and lasts 4 weeks
[Control Center Specific] starts after [Control Center Basic]'s end and lasts 4 weeks

[Autoclicker Basic] starts at [Control Center Specific]'s end and lasts 2 weeks
[Autoclicker Specific] starts at [Autoclicker Basic]'s end and lasts 2 weeks

[Documentation code] starts at [Autoclicker Specific]'s end and lasts 1 weeks

-- Milestones --
[Communicatie done] happens 2023-10-20
[Control Panel Basic done] happens 2023-11-24
[Control Panel done] happens 2023-12-22
[OPLEVERMOMENT 1]  happens 2023-12-22

[Autoclicker Basic done] happens 2024-1-5
[Autoclicker done] happens 2024-1-19
[OPLEVERMOMENT 2] happens 2024-1-19

[Einde stage] happens 2024-2-2
@endgantt